# Generated by Django 5.0.1 on 2024-05-10 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 10, 19, 27, 9, 962248, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
