# Generated by Django 5.0.1 on 2024-05-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoy',
            new_name='category',
        ),
    ]
