# Generated by Django 5.0.1 on 2024-05-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_size_remove_product_sizes_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit.'),
        ),
    ]
