# Generated by Django 5.0.1 on 2024-05-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_before',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
